# Lesson 1: Advanced RAG Pipeline

In [4]:
import utils

import os
import openai
openai.api_key = utils.get_openai_api_key()

In [5]:
from llama_index import SimpleDirectoryReader

documents = SimpleDirectoryReader(
    input_files=["./eBook-How-to-Build-a-Career-in-AI.pdf"]
).load_data()

In [6]:
print(type(documents), "\n")
print(len(documents), "\n")
print(type(documents[0]))
print(documents[0])

<class 'list'>

41

<class 'llama_index.schema.Document'>
Doc ID: c67f1ec8-d9f5-48e2-a798-b5323ba8f049
Text: PAGE 1Founder, DeepLearning.AICollected Insights from Andrew Ng
How to  Build Your Career in AIA Simple Guide

## Basic RAG pipeline

In [7]:
from llama_index import Document

document = Document(text="\n\n".join([doc.text for doc in documents]))

In [8]:
from llama_index import VectorStoreIndex
from llama_index import ServiceContext
from llama_index.llms import OpenAI

llm = OpenAI(model="gpt-3.5-turbo", temperature=0.1)
service_context = ServiceContext.from_defaults(
    llm=llm, embed_model="local:BAAI/bge-small-en-v1.5"
)
index = VectorStoreIndex.from_documents([document],
                                        service_context=service_context)

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

[nltk_data] Downloading package punkt to /tmp/llama_index...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [9]:
query_engine = index.as_query_engine()

In [10]:
response = query_engine.query(
    "What are steps to take when finding projects to build your experience?"
)
print(str(response))

Develop a side hustle, ensure the project will help you grow technically, collaborate with good teammates, and consider if the project can be a stepping stone to larger projects.

## Evaluation setup using TruLens

In [11]:
eval_questions = []
with open('eval_questions.txt', 'r') as file:
    for line in file:
        # Remove newline character and convert to integer
        item = line.strip()
        print(item)
        eval_questions.append(item)

What are the keys to building a career in AI?
How can teamwork contribute to success in AI?
What is the importance of networking in AI?
What are some good habits to develop for a successful career?
How can altruism be beneficial in building a career?
What is imposter syndrome and how does it relate to AI?
Who are some accomplished individuals who have experienced imposter syndrome?
What is the first step to becoming good at AI?
What are some common challenges in AI?
Is it normal to find parts of AI challenging?

In [12]:
# You can try your own question:
new_question = "What is the right AI job for me?"
eval_questions.append(new_question)

In [13]:
print(eval_questions)

['What are the keys to building a career in AI?', 'How can teamwork contribute to success in AI?', 'What is the importance of networking in AI?', 'What are some good habits to develop for a successful career?', 'How can altruism be beneficial in building a career?', 'What is imposter syndrome and how does it relate to AI?', 'Who are some accomplished individuals who have experienced imposter syndrome?', 'What is the first step to becoming good at AI?', 'What are some common challenges in AI?', 'Is it normal to find parts of AI challenging?', 'What is the right AI job for me?']

In [14]:
from trulens_eval import Tru
tru = Tru()

tru.reset_database()

🦑 Tru initialized with db url sqlite:///default.sqlite .
🛑 Secret keys may be written to the database. See the `database_redact_keys` option of `Tru` to prevent this.

For the classroom, we've written some of the code in helper functions inside a utils.py file.  
- You can view the utils.py file in the file directory by clicking on the "Jupyter" logo at the top of the notebook.
- In later lessons, you'll get to work directly with the code that's currently wrapped inside these helper functions, to give you more options to customize your RAG pipeline.

In [15]:
from utils import get_prebuilt_trulens_recorder

tru_recorder = get_prebuilt_trulens_recorder(query_engine,
                                             app_id="Direct Query Engine")

In [16]:
with tru_recorder as recording:
    for question in eval_questions:
        response = query_engine.query(question)

In [17]:
records, feedback = tru.get_records_and_feedback(app_ids=[])

In [18]:
records.head()

,app_id,app_json,type,record_id,input,output,tags,record_json,cost_json,perf_json,ts,Answer Relevance,Context Relevance,Groundedness,Answer Relevance_calls,Context Relevance_calls,Groundedness_calls,latency,total_tokens,total_cost
0,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_e53665bbd01f8189ba8acf3c0bbb69ed,"""What are the keys to building a career in AI?""","""Learning foundational technical skills, worki...",-,"{""record_id"": ""record_hash_e53665bbd01f8189ba8...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-08-17T09:07:51.401369"", ""...",2026-08-17T09:07:52.656888,1.0,1.00,1.000000,[{'args': {'prompt': 'What are the keys to bui...,[{'args': {'prompt': 'What are the keys to bui...,"[{'args': {'source': 'PAGE 1Founder, DeepLearn...",1,2066,0.003123
1,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_7f87efb49c7c3fee8a8cf8c2454c79de,"""How can teamwork contribute to success in AI?""","""Teamwork can contribute to success in AI by a...",-,"{""record_id"": ""record_hash_7f87efb49c7c3fee8a8...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-08-17T09:07:52.773068"", ""...",2026-08-17T09:07:54.491162,1.0,0.50,0.933333,[{'args': {'prompt': 'How can teamwork contrib...,[{'args': {'prompt': 'How can teamwork contrib...,[{'args': {'source': 'Hopefully the previous c...,1,1700,0.002587
2,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_c51cc873b0b30a4ef148fc161a18c7a2,"""What is the importance of networking in AI?""","""Networking is crucial in AI as it helps indiv...",-,"{""record_id"": ""record_hash_c51cc873b0b30a4ef14...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-08-17T09:07:54.607135"", ""...",2026-08-17T09:07:55.916002,1.0,0.10,0.666667,[{'args': {'prompt': 'What is the importance o...,[{'args': {'prompt': 'What is the importance o...,[{'args': {'source': 'Hopefully the previous c...,1,1694,0.002576
3,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_e43be6b14f5d323a8ebb948835dfc53c,"""What are some good habits to develop for a su...","""Developing good habits in areas such as eatin...",-,"{""record_id"": ""record_hash_e43be6b14f5d323a8eb...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-08-17T09:07:56.045507"", ""...",2026-08-17T09:07:56.969955,1.0,0.95,NaN,[{'args': {'prompt': 'What are some good habit...,[{'args': {'prompt': 'What are some good habit...,NaN,0,1632,0.002466
4,Direct Query Engine,"{""app_id"": ""Direct Query Engine"", ""tags"": ""-"",...",RetrieverQueryEngine(llama_index.query_engine....,record_hash_6a030c4e228fe27a2717ef6c2f030651,"""How can altruism be beneficial in building a ...","""Helping others during your career journey can...",-,"{""record_id"": ""record_hash_6a030c4e228fe27a271...","{""n_requests"": 1, ""n_successful_requests"": 1, ...","{""start_time"": ""2026-08-17T09:07:57.080784"", ""...",2026-08-17T09:07:57.854780,1.0,NaN,NaN,[{'args': {'prompt': 'How can altruism be bene...,NaN,NaN,0,1609,0.002421

In [19]:
# launches on http://localhost:8501/
tru.run_dashboard()

Starting dashboard ...
Config file already exists. Skipping writing process.
Credentials file already exists. Skipping writing process.

Accordion(children=(VBox(children=(VBox(children=(Label(value='STDOUT'), Output())), VBox(children=(Label(valu…

Dashboard started at https://s172-29-75-22p38560.lab-aws-production.deeplearning.ai/ .

## Advanced RAG pipeline

### 1. Sentence Window retrieval

In [20]:
from llama_index.llms import OpenAI

llm = OpenAI(model="gpt-3.5-turbo", temperature=0.1)

In [21]:
from utils import build_sentence_window_index

sentence_index = build_sentence_window_index(
    document,
    llm,
    embed_model="local:BAAI/bge-small-en-v1.5",
    save_dir="sentence_index"
)

In [22]:
from utils import get_sentence_window_query_engine

sentence_window_engine = get_sentence_window_query_engine(sentence_index)

config.json:   0%|          | 0.00/799 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/279 [00:00<?, ?B/s]

In [23]:
window_response = sentence_window_engine.query(
    "how do I get started on a personal project in AI?"
)
print(str(window_response))

To get started on a personal project in AI, you can begin by identifying a project that aligns with your career goals and interests. It's important to choose a project that is responsible, ethical, and beneficial to people. Once you have selected a project, you can follow the steps outlined in the chapters provided, such as scoping the project, executing it with an eye toward career development, and building a portfolio that demonstrates skill progression. By following these guidelines, you can embark on a personal AI project that not only enhances your skills but also contributes positively to the field.

In [24]:
tru.reset_database()

tru_recorder_sentence_window = get_prebuilt_trulens_recorder(
    sentence_window_engine,
    app_id = "Sentence Window Query Engine"
)

In [25]:
for question in eval_questions:
    with tru_recorder_sentence_window as recording:
        response = sentence_window_engine.query(question)
        print(question)
        print(str(response))

What are the keys to building a career in AI?
Learning foundational technical skills, working on projects, finding a job, and being part of a supportive community are the keys to building a career in AI.
How can teamwork contribute to success in AI?
Teammates play a crucial role in the success of AI projects. Working with colleagues who are dedicated, continuously learning, and focused on using AI to benefit everyone can positively influence individual performance. Collaborating with a team that shares these values can lead to improved project outcomes and personal growth as a leader in AI projects.
What is the importance of networking in AI?
Networking in AI is crucial as it can provide valuable insights, guidance, and opportunities for individuals looking to advance in the field. By connecting with professionals who have experience in AI, individuals can gain knowledge about the industry, potential career paths, and current trends. Networking also allows individuals to build relationships with others in the field, which can lead to mentorship, collaboration on projects, and even job opportunities. Additionally, networking helps individuals stay informed about the latest developments in AI and can open doors to new connections and resources that can further their career goals.
What are some good habits to develop for a successful career?
Developing good habits in areas such as eating, exercise, sleep, personal relationships, work, learning, and self-care can help individuals move forward in their careers while maintaining their health.
How can altruism be beneficial in building a career?
Helping others along the way can actually benefit one's career development.
What is imposter syndrome and how does it relate to AI?
Imposter syndrome is a phenomenon where individuals doubt their accomplishments and have a persistent fear of being exposed as a fraud. In the context of AI, newcomers to the field may experience imposter syndrome, feeling like they do not truly belong in the AI community despite their success. This can be a significant challenge for individuals in AI, as it may hinder their growth and progress in the field.
Who are some accomplished individuals who have experienced imposter syndrome?
Former Facebook COO Sheryl Sandberg, U.S. first lady Michelle Obama, actor Tom Hanks, and Atlassian co-CEO Mike Cannon-Brookes.
What is the first step to becoming good at AI?
Identifying possible roles and conducting informational interviews.
What are some common challenges in AI?
Common challenges in AI include the evolving nature of technologies, the need to continuously update skills due to rapid changes in technology, difficulties in project management due to the iterative nature of AI projects, challenges in collaborating with stakeholders who lack AI expertise, and the complexity of understanding and implementing AI research papers and techniques.
Is it normal to find parts of AI challenging?
It is normal to find parts of AI challenging.
What is the right AI job for me?
The right AI job for you can be found by following the steps outlined in Chapter 9: Finding the Right AI Job for You. By utilizing the simple framework for starting your AI job search, building a portfolio of projects that show skill progression, and using informational interviews to find the right job, you can identify the AI job that aligns with your career goals and aspirations.

In [26]:
tru.get_leaderboard(app_ids=[])

                              Answer Relevance   latency  total_cost
app_id
Sentence Window Query Engine             0.975  1.181818    0.000806

In [27]:
# launches on http://localhost:8501/
tru.run_dashboard()

Starting dashboard ...
Config file already exists. Skipping writing process.
Credentials file already exists. Skipping writing process.
Dashboard already running at path: https://s172-29-75-22p38560.lab-aws-production.deeplearning.ai/

### 2. Auto-merging retrieval

In [28]:
from utils import build_automerging_index

automerging_index = build_automerging_index(
    documents,
    llm,
    embed_model="local:BAAI/bge-small-en-v1.5",
    save_dir="merging_index"
)

In [29]:
from utils import get_automerging_query_engine

automerging_query_engine = get_automerging_query_engine(
    automerging_index,
)

In [30]:
auto_merging_response = automerging_query_engine.query(
    "How do I build a portfolio of AI projects?"
)
print(str(auto_merging_response))

> Merging 1 nodes into parent node.
> Parent node id: 402742f2-4acc-4a5f-b8ef-2f54db18f1fb.
> Parent node text: PAGE 21Building a Portfolio of
Projects that Shows
Skill Progression CHAPTER 6
PROJECTS

> Merging 1 nodes into parent node.
> Parent node id: 6538b901-43ca-4f4a-bae4-0e10b7c9ea8b.
> Parent node text: PAGE 21Building a Portfolio of
Projects that Shows
Skill Progression CHAPTER 6
PROJECTS

Building a portfolio of AI projects involves showcasing a progression from simple to complex undertakings over time. It is important to be able to effectively communicate your thought process to demonstrate the value of your work and gain the trust of others for larger projects. Identifying worthwhile ideas to work on is a crucial skill for an AI architect, and gaining experience through working on projects across various industries can help in building a diverse and impactful portfolio.

In [31]:
tru.reset_database()

tru_recorder_automerging = get_prebuilt_trulens_recorder(automerging_query_engine,
                                                         app_id="Automerging Query Engine")

In [32]:
for question in eval_questions:
    with tru_recorder_automerging as recording:
        response = automerging_query_engine.query(question)
        print(question)
        print(response)

> Merging 2 nodes into parent node.
> Parent node id: acc6e0d7-297e-4236-a40d-980a1744370f.
> Parent node text: PAGE 3Table of
ContentsIntroduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to Ca...

> Merging 1 nodes into parent node.
> Parent node id: 1503e5ff-1866-4e50-b5a2-9f5444126fa5.
> Parent node text: PAGE 3Table of
ContentsIntroduction: Coding AI is the New Literacy.
Chapter 1: Three Steps to Ca...

What are the keys to building a career in AI?
Learning foundational technical skills, working on projects, finding a job, and being part of a community are key steps to building a career in AI. Additionally, collaborating with others, influencing, and being influenced by others are critical aspects for success in AI.
How can teamwork contribute to success in AI?
Teamwork can contribute to success in AI by allowing individuals to work together effectively on large projects. Collaborating in teams enables individuals to leverage each other's strengths, share knowledge, and collectively solve complex problems. Additionally, the ability to collaborate, influence others, and be influenced by others is crucial in the field of AI, emphasizing the importance of teamwork in achieving success.
> Merging 3 nodes into parent node.
> Parent node id: 81ac4537-fe11-4253-8201-adc631c13228.
> Parent node text: PAGE 35Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more comple...

> Merging 1 nodes into parent node.
> Parent node id: 70699d3c-17e1-4956-9592-0ada76653e98.
> Parent node text: PAGE 35Keys to Building a Career in AI CHAPTER 10
The path to career success in AI is more comple...

What is the importance of networking in AI?
Networking in AI is crucial as it helps individuals build a strong professional network within the industry. This network can provide support, guidance, and opportunities for career advancement. By connecting with others in the field, individuals can gain valuable insights, stay updated on industry trends, and potentially find mentors who can help them navigate their career paths effectively.
> Merging 2 nodes into parent node.
> Parent node id: 9287f669-1dbb-4e64-ae51-be096e143656.
> Parent node text: PAGE 36Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
on...

> Merging 2 nodes into parent node.
> Parent node id: 16bd93a1-3bbc-44d2-91c8-ae485a69f152.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

> Merging 1 nodes into parent node.
> Parent node id: 67defe7b-a166-4447-b4c3-d6cd8d546f4b.
> Parent node text: PAGE 36Keys to Building a Career in AI CHAPTER 10
Of all the steps in building a career, this
on...

> Merging 1 nodes into parent node.
> Parent node id: fc5477cd-f58b-4a10-8b86-bb0b0ef1f026.
> Parent node text: PAGE 11
The Best Way to Build
a New Habit
One of my favorite books is BJ Fogg’s, Tiny Habits: Th...

What are some good habits to develop for a successful career?
Good habits to develop for a successful career include habits related to eating well, exercising regularly, getting enough sleep, maintaining positive personal relationships, consistently working towards learning and self-improvement, and practicing self-care. These habits can help individuals progress in their careers while also ensuring their overall well-being.
> Merging 2 nodes into parent node.
> Parent node id: b4867dbc-7503-4f68-8646-de1c3d79a515.
> Parent node text: PAGE 30Finding someone to interview isn’t always easy, but many people who are in senior position...

> Merging 1 nodes into parent node.
> Parent node id: 9275a7fa-3823-459b-a0c4-45a60614f437.
> Parent node text: PAGE 30Finding someone to interview isn’t always easy, but many people who are in senior position...

How can altruism be beneficial in building a career?
Altruism can be beneficial in building a career by creating opportunities for networking and mentorship. By helping others and lifting them up during their journey, individuals can establish strong relationships within their industry. This can lead to receiving support and guidance from experienced professionals, opening doors to new opportunities, and potentially receiving referrals to potential employers. Ultimately, practicing altruism can contribute to a positive reputation, a supportive network, and a fulfilling career path.
> Merging 5 nodes into parent node.
> Parent node id: 63d11b35-60da-4273-ba5b-87b376cab089.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: 941f44ba-81dc-410f-aa31-de14d845bca4.
> Parent node text: PAGE 37Overcoming Imposter
SyndromeCHAPTER 11

> Merging 3 nodes into parent node.
> Parent node id: ba061e6e-d240-467e-a904-365a5b72abbd.
> Parent node text: PAGE 39My three-year-old daughter (who can barely count to 12) regularly tries to teach things to...

> Merging 1 nodes into parent node.
> Parent node id: a766f603-017e-4be8-ad1c-09aaa9d2d227.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: f30647b0-1802-4e70-bbfb-a91e3733395a.
> Parent node text: PAGE 37Overcoming Imposter
SyndromeCHAPTER 11

> Merging 1 nodes into parent node.
> Parent node id: f27dec3e-5af4-486d-8a41-99949579d745.
> Parent node text: PAGE 39My three-year-old daughter (who can barely count to 12) regularly tries to teach things to...

What is imposter syndrome and how does it relate to AI?
Imposter syndrome is when individuals doubt their abilities and feel like a fraud despite their accomplishments. In the context of AI, newcomers to the field may experience imposter syndrome as they navigate the technically complex nature of artificial intelligence. It is highlighted that even accomplished individuals in the AI community have faced imposter syndrome at some point. The message conveyed is that struggling with challenges in AI is a common experience and should not deter anyone from pursuing a career in the field.
> Merging 3 nodes into parent node.
> Parent node id: 63d11b35-60da-4273-ba5b-87b376cab089.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: 941f44ba-81dc-410f-aa31-de14d845bca4.
> Parent node text: PAGE 37Overcoming Imposter
SyndromeCHAPTER 11

> Merging 3 nodes into parent node.
> Parent node id: ba061e6e-d240-467e-a904-365a5b72abbd.
> Parent node text: PAGE 39My three-year-old daughter (who can barely count to 12) regularly tries to teach things to...

> Merging 1 nodes into parent node.
> Parent node id: a766f603-017e-4be8-ad1c-09aaa9d2d227.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: f30647b0-1802-4e70-bbfb-a91e3733395a.
> Parent node text: PAGE 37Overcoming Imposter
SyndromeCHAPTER 11

> Merging 1 nodes into parent node.
> Parent node id: f27dec3e-5af4-486d-8a41-99949579d745.
> Parent node text: PAGE 39My three-year-old daughter (who can barely count to 12) regularly tries to teach things to...

Who are some accomplished individuals who have experienced imposter syndrome?
Sheryl Sandberg, Michelle Obama, Tom Hanks, and Mike Cannon-Brookes are some accomplished individuals who have experienced imposter syndrome.
What is the first step to becoming good at AI?
The first step to becoming good at AI is to suck at it.
What are some common challenges in AI?
Some common challenges in AI include the highly iterative nature of AI projects, uncertainty in planning due to not knowing in advance how long it will take to achieve target accuracy, and facing technical challenges that even experienced professionals have encountered.
> Merging 3 nodes into parent node.
> Parent node id: 63d11b35-60da-4273-ba5b-87b376cab089.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

> Merging 1 nodes into parent node.
> Parent node id: a766f603-017e-4be8-ad1c-09aaa9d2d227.
> Parent node text: PAGE 38Before we dive into the final chapter of this book, I’d like to address the serious matter...

Is it normal to find parts of AI challenging?
It is normal to find parts of AI challenging.
> Merging 1 nodes into parent node.
> Parent node id: 0c6adbe2-c743-4dfe-b0c8-e45e9fa8c680.
> Parent node text: PAGE 31Finding the Right
AI Job for YouCHAPTER 9
JOBS

> Merging 1 nodes into parent node.
> Parent node id: c5859b9f-f0a5-43aa-bb2d-593e5c2283c5.
> Parent node text: If you’re leaving
a job, exit gracefully. Give your employer ample notice, give your full effort...

> Merging 1 nodes into parent node.
> Parent node id: dc4f1a8e-5b0d-4051-ae47-d8d677c8fa3d.
> Parent node text: PAGE 28Using Informational
Interviews to Find
the Right JobCHAPTER 8
JOBS

> Merging 1 nodes into parent node.
> Parent node id: c5ae7f24-8c96-41a1-a5ef-3f9a9ab0b259.
> Parent node text: PAGE 31Finding the Right
AI Job for YouCHAPTER 9
JOBS

> Merging 1 nodes into parent node.
> Parent node id: 29c01593-7a66-40db-a2ac-dd99c2a60743.
> Parent node text: PAGE 28Using Informational
Interviews to Find
the Right JobCHAPTER 8
JOBS

What is the right AI job for me?
The right AI job for you would likely depend on whether you are looking to switch roles, industries, or both. If you are seeking your first job in AI, transitioning either roles or industries individually may be easier than attempting both simultaneously.

In [33]:
tru.get_leaderboard(app_ids=[])

                          Answer Relevance  latency  total_cost
app_id
Automerging Query Engine               1.0      2.0    0.000868

In [34]:
# launches on http://localhost:8501/
tru.run_dashboard()

Starting dashboard ...
Config file already exists. Skipping writing process.
Credentials file already exists. Skipping writing process.
Dashboard already running at path: https://s172-29-75-22p38560.lab-aws-production.deeplearning.ai/